version: '3.1'

services:
  db:
    image: postgres:15.1-alpine
    container_name: mydb
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_api
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'

volumes:
  db_data:
